CREATE TABLE push_subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    nearby_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    climatic_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    civil_defense_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP(6) WITH TIME ZONE,
    failure_count INT NOT NULL DEFAULT 0,
    daily_sent_count INT NOT NULL DEFAULT 0,
    daily_count_date DATE,
    CONSTRAINT uq_push_subscription_endpoint UNIQUE (endpoint)
);
