CREATE TABLE push_delivery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    dedup_key TEXT NOT NULL,
    sent_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status TEXT NOT NULL,
    CONSTRAINT fk_push_delivery_subscription FOREIGN KEY (subscription_id) REFERENCES push_subscription (id) ON DELETE CASCADE,
    CONSTRAINT uq_push_delivery_subscription_dedup UNIQUE (subscription_id, dedup_key)
);
