CREATE TABLE alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255) NOT NULL CHECK (type IN ('USER', 'CLIMATIC', 'CIVIL_DEFENSE')),
    username VARCHAR(255) NOT NULL,
    location GEOMETRY(POINT, 4326) NOT NULL,
    expiration_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    creation_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE alert_photo (
    alert_id BIGINT NOT NULL,
    photo_path VARCHAR(255),
    CONSTRAINT fk_alert_photo_alert FOREIGN KEY (alert_id) REFERENCES alert (id)
);
