CREATE TABLE civil_defense_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT NOT NULL,
    title VARCHAR(500) NOT NULL,
    excerpt TEXT,
    content TEXT,
    link VARCHAR(1000),
    risk_level VARCHAR(20) NOT NULL CHECK (risk_level IN ('ATTENTION', 'ALERT', 'EMERGENCY')),
    published_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_civil_defense_notice_external_id UNIQUE (external_id)
);
