import { httpAlertClient } from "@/api/httpAlertClient";
import { httpAdminClient } from "@/api/httpAdminClient";
import { httpAuthClient } from "@/api/httpAuthClient";
import { httpCameraClient } from "@/api/httpCameraClient";
import { httpCivilDefenseClient } from "@/api/httpCivilDefenseClient";
import { httpPushClient } from "@/api/httpPushClient";
import { httpPresenceClient } from "@/api/httpPresenceClient";
import { httpRecentAlertsClient } from "@/api/httpRecentAlertsClient";
import { httpWeatherClient } from "@/api/httpWeatherClient";
import { httpZoneClient } from "@/api/httpZoneClient";
import type { AdminClient } from "@/api/adminClient";
import type { AlertClient } from "@/api/alertClient";
import type { AuthClient } from "@/api/authClient";
import type { CameraClient } from "@/api/cameraClient";
import type { CivilDefenseClient } from "@/api/civilDefenseClient";
import type { PushClient } from "@/api/pushClient";
import type { PresenceClient } from "@/api/presenceClient";
import type { RecentAlertsClient } from "@/api/recentAlertsClient";
import type { WeatherClient } from "@/api/weatherClient";
import type { ZoneClient } from "@/api/zoneClient";

export const adminClient: AdminClient = httpAdminClient;
export const alertClient: AlertClient = httpAlertClient;
export const authClient: AuthClient = httpAuthClient;
export const cameraClient: CameraClient = httpCameraClient;
export const civilDefenseClient: CivilDefenseClient = httpCivilDefenseClient;
export const pushClient: PushClient = httpPushClient;
export const presenceClient: PresenceClient = httpPresenceClient;
export const recentAlertsClient: RecentAlertsClient = httpRecentAlertsClient;
export const weatherClient: WeatherClient = httpWeatherClient;
export const zoneClient: ZoneClient = httpZoneClient;

export type { AdminClient } from "@/api/adminClient";
export type { AlertClient } from "@/api/alertClient";
export type { AuthClient } from "@/api/authClient";
export type { CameraClient } from "@/api/cameraClient";
export type { CivilDefenseClient } from "@/api/civilDefenseClient";
export type { PushClient } from "@/api/pushClient";
export type { PresenceClient } from "@/api/presenceClient";
export type { RecentAlertsClient } from "@/api/recentAlertsClient";
export type { WeatherClient } from "@/api/weatherClient";
export type { ZoneClient } from "@/api/zoneClient";
